-- Criação da tabela de Comarcas
CREATE TABLE IF NOT EXISTS public.dcomarcas (
  idcomarca SERIAL PRIMARY KEY,
  comarca TEXT NOT NULL,
  entrancia TEXT CHECK (entrancia IN ('1ª Entrância', '2ª Entrância', '3ª Entrância')),
  polo TEXT NOT NULL,
  regiao TEXT NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.dcomarcas ENABLE ROW LEVEL SECURITY;

-- Política de acesso: Todos (autenticados ou anônimos) podem ler a lista de comarcas
CREATE POLICY "Comarcas visíveis para todos" 
ON public.dcomarcas FOR SELECT USING (true);

-- Inserção dos 144 registros de comarcas (Dados Fictícios/Estimados para Estrutura)
INSERT INTO public.dcomarcas (comarca, entrancia, polo, regiao) VALUES
('Abaetetuba', '2ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Abel Figueiredo', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Acará', '1ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Afuá', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Água Azul do Norte', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Alenquer', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Almeirim', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Altamira', '3ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Anajás', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Ananindeua', '3ª Entrância', 'Pólo Ananindeua', '2ª Região Judiciária'),
('Anapu', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Augusto Corrêa', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Aurora do Pará', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Aveiro', '1ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Bagre', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Baião', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Bannach', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Barcarena', '2ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Belém', '3ª Entrância', 'Pólo Belém', '1ª Região Judiciária'),
('Belterra', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Benevides', '2ª Entrância', 'Pólo Ananindeua', '2ª Região Judiciária'),
('Bom Jesus do Tocantins', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Bonito', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Bragança', '2ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Brasil Novo', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Brejo Grande do Araguaia', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Breu Branco', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Breves', '2ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Bujaru', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Cachoeira do Arari', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Cachoeira do Piriá', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Cametá', '2ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Canaã dos Carajás', '2ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Capanema', '2ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Capitão Poço', '2ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Castanhal', '3ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Chaves', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Colares', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Conceição do Araguaia', '2ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Concórdia do Pará', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Cumaru do Norte', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Curionópolis', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Curralinho', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Curuá', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Curuçá', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Dom Eliseu', '1ª Entrância', 'Pólo Paragominas', '13ª Região Judiciária'),
('Eldorado do Carajás', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Faro', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Floresta do Araguaia', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Garrafão do Norte', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Goianésia do Pará', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Gurupá', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Igarapé-Açu', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Igarapé-Miri', '1ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Inhangapi', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Ipixuna do Pará', '1ª Entrância', 'Pólo Paragominas', '13ª Região Judiciária'),
('Irituia', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Itaituba', '2ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Itupiranga', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Jacareacanga', '1ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Jacundá', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Juruti', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Limoeiro do Ajuru', '1ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Mãe do Rio', '1ª Entrância', 'Pólo Paragominas', '13ª Região Judiciária'),
('Magalhães Barata', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Marabá', '3ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Maracanã', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Marapanim', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Marituba', '3ª Entrância', 'Pólo Ananindeua', '2ª Região Judiciária'),
('Medicilândia', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Melgaço', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Mocajuba', '1ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Moju', '1ª Entrância', 'Pólo Abaetetuba', '9ª Região Judiciária'),
('Mojuí dos Campos', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Monte Alegre', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Muaná', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Nova Esperança do Piriá', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Nova Ipixuna', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Nova Timboteua', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Novo Progresso', '1ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Novo Repartimento', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Óbidos', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Oeiras do Pará', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Oriximiná', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Ourém', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Ourilândia do Norte', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Pacajá', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Palestina do Pará', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Paragominas', '2ª Entrância', 'Pólo Paragominas', '13ª Região Judiciária'),
('Parauapebas', '3ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Pau D''Arco', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Peixe-Boi', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Piçarra', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Placas', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Ponta de Pedras', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Portel', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Porto de Moz', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Prainha', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Primavera', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Quatipuru', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Redenção', '2ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Rio Maria', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Rondon do Pará', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('Rurópolis', '1ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Salinópolis', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Salvaterra', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Santa Bárbara do Pará', '1ª Entrância', 'Pólo Ananindeua', '2ª Região Judiciária'),
('Santa Cruz do Arari', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Santa Isabel do Pará', '2ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Santa Luzia do Pará', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Santa Maria das Barreiras', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Santa Maria do Pará', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Santana do Araguaia', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Santarém', '3ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Santarém Novo', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Santo Antônio do Tauá', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São Caetano de Odivelas', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São Domingos do Araguaia', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('São Domingos do Capim', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São Félix do Xingu', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('São Francisco do Pará', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São Geraldo do Araguaia', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('São João da Ponta', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São João de Pirabas', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('São João do Araguaia', '1ª Entrância', 'Pólo Marabá', '4ª Região Judiciária'),
('São Miguel do Guamá', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('São Sebastião da Boa Vista', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Sapucaia', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Senador José Porfírio', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Soure', '1ª Entrância', 'Pólo Breves', '11ª Região Judiciária'),
('Tailândia', '1ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Terra Alta', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Terra Santa', '1ª Entrância', 'Pólo Santarém', '3ª Região Judiciária'),
('Tomé-Açu', '1ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Tracuateua', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Trairão', '1ª Entrância', 'Pólo Itaituba', '10ª Região Judiciária'),
('Tucumã', '1ª Entrância', 'Pólo Redenção', '8ª Região Judiciária'),
('Tucuruí', '2ª Entrância', 'Pólo Tucuruí', '7ª Região Judiciária'),
('Ulianópolis', '1ª Entrância', 'Pólo Paragominas', '13ª Região Judiciária'),
('Uruará', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Vigia', '2ª Entrância', 'Pólo Castanhal', '5ª Região Judiciária'),
('Viseu', '1ª Entrância', 'Pólo Capanema', '12ª Região Judiciária'),
('Vitória do Xingu', '1ª Entrância', 'Pólo Altamira', '6ª Região Judiciária'),
('Xinguara', '2ª Entrância', 'Pólo Redenção', '8ª Região Judiciária');
